title: Murrahjm.Github.io # your site title
author: Jeremy Murrah
email: murrahjm@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://murrahjm.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jeremymurrah # replace with your_twitter_username or comment to remove link from footer
github_username:  murrahjm # replace with your_github_username or comment to remove link from footer
#instagram_username: murrahjm # replace with your_instagram_username or comment to remove link from footer
social:
  name: Jeremy Murrah
  links:
    - https://twitter.com/JeremyMurrah
    - https://www.facebook.com/Jeremy.Murrah
    - https://www.linkedin.com/in/JeremyMurrah
    - https://plus.google.com/+JeremyMurrah
    - https://github.com/murrahjm

disqus:
  shortname: jeremymurrah # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
