title: Murrahjm.Github.io # your site title
author: Jeremy Murrah
email: murrahjm@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Blog for all things PowerShell and Automation.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://murrahjm.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jeremymurrah # replace with your_twitter_username or comment to remove link from footer
github_username:  murrahjm # replace with your_github_username or comment to remove link from footer
linkedin_username: jeremymurrah
#instagram_username: murrahjm # replace with your_instagram_username or comment to remove link from footer
social:
  name: Jeremy Murrah
  links:
    - https://twitter.com/JeremyMurrah
    - https://www.facebook.com/Jeremy.Murrah
    - https://www.linkedin.com/in/JeremyMurrah
    - https://plus.google.com/+JeremyMurrah
    - https://github.com/murrahjm

footer-links:
  email: murrahjm@gmail.com
  github: murrahjm
  linkedin: jeremymurrah
  twitter: JeremyMurrah
  sqlshack_2018: 50
  
disqus:
  shortname: murrahjm-github-io # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
#comment out theme property to avoid warnings about unsupported theme from github pages
#theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins_dir:
  - jekyll-sitemap
  - jekyll-seo-tag
